### ISSUE TITLE
Lỗi nút Registration

### ISSUE THREAD

**Issue by Anh39** [Anh39/Sofware-Engineering#10]
#6 
Xảy ra lỗi khi nhấn vào nút đăng nhập.

script.js:53 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at script.js:53:16

**Comment by dphieu** [comment]
đã sửa lỗi:
viết sai id của RegisterButton
=> const RegisterButton = document.querySelector('#Register')
