### ISSUE TITLE
Đổi giao diện khi đăng nhập thành công

### ISSUE THREAD

**Issue by Anh39** [Anh39/Sofware-Engineering#16]
Cần đổi giao diện khi đăng nhập thành công và khi đăng ký thành công ( tự động đăng nhập khi đăng ký thành công)

**Comment by dphieu** [comment]
Hoàn thành giao diện khi đăng nhập được. 
Còn thiếu sự kết nối giữa giữa backend và frontend (mới) để thử nghiệm
