### ISSUE TITLE
Ý kiến thêm tính năng

### ISSUE THREAD

**Issue by Anh39** [Anh39/Sofware-Engineering#2]
Ý kiến về các tính năng đang đề ra (loại bỏ hoặc thêm)

**Comment by Anh39** [comment]
Làm mô hình dịch ? Chắc là cho vào phần tính năng nâng cao. Hiện tại mới chỉ thông qua các API để xây dựng ứng dụng thử nghiệm.

**Comment by dphieu** [comment]
quan trọng là quá trình, chứ ko phải làm phần mềm phức tạp lên, nên có thể thêm vào nếu có thời gian
