### ISSUE TITLE
Phân chia công việc

### ISSUE THREAD

**Issue by Anh39** [Anh39/Sofware-Engineering#3]
Phân chia công việc cơ bản cho mỗi người, tạm thời tính các phần chức năng cơ bản, chưa tính đến các tính năng nâng cao. Mọi người tự nhận công việc của mình.

**Comment by Anh39** [comment]
Phần backend của server (các request/ phân luồng xử lý request) do mình đảm nhiệm

**Comment by dphieu** [comment]
mk sẽ làm frontend nhanh nhất có thể
